### ISSUE TITLE
Agasha Mystic School 

### ISSUE THREAD

**Issue by yngtnrpdx** [dashnine/PaperBlossoms#186] opened 2020-07-18 00:22 UTC
I think that the invocation Tempest of Air granted at character creation for this school should be Tetsubo of Earth. 
thank you all for the wonderful program.

**Comment by dashnine** [comment] 2020-07-31 17:10
We actually have fixed that -- closing this as a duplicate of #181.  Resolved in commit: https://github.com/dashnine/PaperBlossoms/commit/c5211a813f37b4b68234bea47d8d67180a1a8bd9

You should see the fix whenever we next release! :-D

Thanks for the report!

**Closed by dashnine** 2020-07-31 17:10 UTC

**Comment by yngtnrpdx** [comment] 2020-08-03 21:23
Now i see it, sorry first time using the site thank you for the reply.

**Comment by dashnine** [comment] 2020-08-03 21:38
No problem at all!  Thanks for the report. :)
