### ISSUE TITLE
Advancement Charts missing

### ISSUE THREAD

**Issue by Isolveth** [dashnine/PaperBlossoms#206] opened 2020-09-19 00:59 UTC
After successful character creation, there is no advancement chart on the left side of paper blossoms underneath the advancement tab. 

Loaded one character created in version 1.2.2. Loaded in Version 1.3.1 and Version 1.3.0 with no advancement chart. Created a new character in 1.3.1 and still no advancement chart. The first capture is the character created in version 1.2.2.  The second image is a new character (showing no chart),

I am unsure what is going on and I am still confirming with my gaming group if they are also seeing the same problem.

![Capture 2](https://user-images.githubusercontent.com/71534187/93655476-2ca61700-f9e9-11ea-8923-baa4a1dad4bd.PNG)
![Capture 1](https://user-images.githubusercontent.com/71534187/93655477-2d3ead80-f9e9-11ea-863e-1146c6341a26.PNG)

**Comment by dashnine** [comment] 2020-09-19 02:56
This looks like the database failed up be updated when you first ran the new build -- this can be caused by the DB being locked (say, due to being open with another instance of paperblossoms.exe), permissions, etc.  Try this:

Tools->Open application Directory
You should see a file called paperblossoms -- that's the db.  Close the Paper Blossoms application.
Rename the paperblossoms.db file to something (paperblossoms.backup, for instance) and then start again.  It should regenerate the database and include all the new content.
This appears to most commonly be caused by something else having the DB open when you attempt an update, or by the prior DB being installed with different permissions (i.e. admin).

Does that get you fixed?

**Comment by Isolveth** [comment] 2020-09-21 22:20
Yes, that fixed it. Thank you very much!

**Comment by dashnine** [comment] 2020-09-22 17:35
Closing for now.  I'd like to know why some of these aren't getting updated, but it looks like it's different reasons.  Looking at doing updates to change how DB updates are detected and run

**Closed by dashnine** 2020-09-22 17:35 UTC
